=== HAdrian0205/UY5E1L_XMLGyak/XMLTaskUY5E1L/XML&XSD/XMLTaskUY5E1L.xsd
<?xml version = "1.0" encoding = "utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Saját típusok (Attribútum) -->

    <xs:simpleType name="statuszTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="aktív" />
            <xs:enumeration value="fizetésre vár" />
            <xs:enumeration value="teljesítve" />
            <xs:enumeration value="törölve" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fizetesTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="online" />
            <xs:enumeration value="utánvét" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="akcioTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen" />
            <xs:enumeration value="nem" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Saját típusok (Element) -->

    <xs:simpleType name="telszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+36\d{9}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="emailTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="afaTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+%" />
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Elementek -->

    <!-- Ügyfél (+cím adatok a szállítónál is) -->
    <xs:element name="vezeteknev" type="xs:string" />
    <xs:element name="keresztnev" type="xs:string" />
    <xs:element name="iranyitoszam" type="xs:int" />
    <xs:element name="varos" type="xs:string" />
    <xs:element name="kozterneve" type="xs:string" />
    <xs:element name="hazszam" type="xs:int" />
    <xs:element name="telefonszam" type="telszamTipus" />
    <xs:element name="email" type="emailTipus" />

    <!-- Ügy-Re -->
    <xs:element name="megjegyzes" type="xs:string" />

    <!-- Rendelés -->
    <xs:element name="osszeg" type="xs:float" />
    <xs:element name="datum" type="xs:date" />

    <!-- Rendelt Termék -->
    <xs:element name="egysegar" type="xs:float" />
    <xs:element name="afa" type="afaTipus" />
    <xs:element name="mennyiseg" type="xs:int" />

    <!-- Termék (+a név a szállítónál is) -->
    <xs:element name="nev" type="xs:string" />
    <xs:element name="ar" type="xs:float" />

    <!-- Szállító -->
    <xs:element name="szallitasiar" />

    <!-- Struktúra megadása -->
    <xs:element name="webshop">
        <xs:complexType>
            <xs:sequence>

                <!-- Ügyfelek -->
                <xs:element name="ugyfel" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="vezeteknev" minOccurs="1" maxOccurs="1" />
                                        <xs:element ref="keresztnev" minOccurs="1" maxOccurs="1" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="lakcim" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="iranyitoszam" minOccurs="1" maxOccurs="1" />
                                        <xs:element ref="varos" minOccurs="0" maxOccurs="1" />
                                        <xs:element ref="kozterneve" minOccurs="1" maxOccurs="1" />
                                        <xs:element ref="hazszam" minOccurs="1" maxOccurs="1" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element ref="telefonszam" minOccurs="1" maxOccurs="1" />
                            <xs:element ref="email" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                        <xs:attribute name="ugyfelid" type="xs:int" use="required" />
                    </xs:complexType>
                </xs:element>
                
                <!-- Kapcsolótábla (Ügy-Re) -->
                <xs:element name="ugyre" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="megjegyzes" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                        <xs:attribute name="megjegyzesid" type="xs:int" use="required" />
                        <xs:attribute name="ugyfelid" type="xs:int" use="required" />
                        <xs:attribute name="rendelesid" type="xs:int" use="required" />
                    </xs:complexType>

                    <!-- Megjegyzés ID (kulcs) -->
                    <xs:key name="megjegyzes_key">
                        <xs:selector xpath="ugyre"></xs:selector>
                        <xs:field xpath="@megjegyzesid"></xs:field>
                    </xs:key>

                    <!-- Megjegyzés idegen kulcsok -->
                    <xs:keyref name="ugyre_ugyfel_fkey" refer="ugyfel_key">
                        <xs:selector xpath="megjegyzes"></xs:selector>
                        <xs:field xpath="@ugyfelid"></xs:field>
                    </xs:keyref>

                    <xs:keyref name="ugyre_rendeles_fkey" refer="rendeles_key">
                        <xs:selector xpath="megjegyzes"></xs:selector>
                        <xs:field xpath="@ugyfelid"></xs:field>
                    </xs:keyref>
                </xs:element>

                <!-- Rendelések  -->
                <xs:element name="rendeles" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="osszeg" minOccurs="1" maxOccurs="1" />
                            <xs:element ref="datum" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                        <xs:attribute name="rendelesid" type="xs:int" use="required" />
                        <xs:attribute name="statusz" type="statuszTipus" use="required" />
                        <xs:attribute name="fizetestipusa" type="fizetesTipus" use="required" />
                        <xs:attribute name="ugyfelid" type="xs:int" use="required" />
                        <xs:attribute name="szallitoid" type="xs:int" use="required" />
                    </xs:complexType>
                </xs:element>

                <!-- Rendelt Termékek -->
                <xs:element name="rendelttermek" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="egysegar" minOccurs="1" maxOccurs="1" />
                            <xs:element ref="afa" minOccurs="1" maxOccurs="1" />
                            <xs:element ref="mennyiseg" maxOccurs="1" />
                        </xs:sequence>
                        <xs:attribute name="rendelttermekid" type="xs:int" use="required" />
                        <xs:attribute name="rendelesid" type="xs:int" use="required" />
                    </xs:complexType>
                </xs:element>

                <!-- Termékek -->
                <xs:element name="termek" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="nev" minOccurs="1" maxOccurs="1" />
                            <xs:element ref="ar" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                        <xs:attribute name="termekid" type="xs:int" use="required" />
                        <xs:attribute name="akcios" type="akcioTipus" use="required" />
                    </xs:complexType>
                </xs:element>

                <!-- Szállító -->
                <xs:element name="szallito" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="nev" minOccurs="1" maxOccurs="1" />
                            <xs:element ref="telefonszam" minOccurs="1" maxOccurs="1" />
                            <xs:element ref="szallitasiar" minOccurs="1" maxOccurs="1" />
                            <xs:element name="kozpontcime">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="iranyitoszam" minOccurs="1" maxOccurs="1" />
                                        <xs:element ref="varos" minOccurs="0" maxOccurs="1" />
                                        <xs:element ref="kozterneve" minOccurs="1" maxOccurs="1" />
                                        <xs:element ref="hazszam" minOccurs="1" maxOccurs="1" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="szallitoid" type="xs:int" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <!-- Rendelés ID (kulcs) -->
        <xs:key name="rendelttermek_key">
            <xs:selector xpath="rendelttermek"></xs:selector>
            <xs:field xpath="@rendelttermekid"></xs:field>
        </xs:key>

        <!-- Szállító ID (kulcs) -->
        <xs:key name="szallito_key">
            <xs:selector xpath="szallito"></xs:selector>
            <xs:field xpath="@szallitoid"></xs:field>
        </xs:key>

        <!-- Termék ID (kulcs) -->
        <xs:key name="termek_key">
            <xs:selector xpath="termek"></xs:selector>
            <xs:field xpath="@termekid"></xs:field>
        </xs:key>

        <!-- Ügyfél ID (kulcs) -->
        <xs:key name="ugyfel_key">
            <xs:selector xpath="ugyfel"></xs:selector>
            <xs:field xpath="@ugyfelid"></xs:field>
        </xs:key>

        <!-- Rendelés ID (kulcs) -->
        <xs:key name="rendeles_key">
            <xs:selector xpath="rendeles"></xs:selector>
            <xs:field xpath="@rendelesid"></xs:field>
        </xs:key>

        <!-- Rendelés idegen kulcsok -->
        <xs:keyref name="rendeles_ugyfel_fkey" refer="ugyfel_key">
            <xs:selector xpath="rendeles"></xs:selector>
            <xs:field xpath="@ugyfelid"></xs:field>
        </xs:keyref>
        
        <xs:keyref name="rendeles_szallito_fkey" refer="szallito_key">
            <xs:selector xpath="rendeles"></xs:selector>
            <xs:field xpath="@szallitoid"></xs:field>
        </xs:keyref>

        <!-- Rendelt Termék idegen kulcsok -->
        <xs:keyref name="rendelttermek_termek_fkey" refer="termek_key">
            <xs:selector xpath="rendelttermek"></xs:selector>
            <xs:field xpath="@termekid"></xs:field>
        </xs:keyref>

        <xs:keyref name="rendelttermek_rendeles_fkey" refer="rendeles_key">
            <xs:selector xpath="rendelttermek"></xs:selector>
            <xs:field xpath="@rendelesid"></xs:field>
        </xs:keyref>

        <!-- Ret-Ter 1:1 kapcsolat -->
        <xs:unique name="ret_ter">
            <xs:selector xpath="rendelttermek" />
            <xs:field xpath="@termekid" />
        </xs:unique>
    </xs:element>

</xs:schema>

=== HAdrian0205/UY5E1L_XMLGyak/XMLTaskUY5E1L/Java/DOMParseUY5E1L/XMLReadGJ2N7R.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><webshop xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLTaskUY5E1L.xsd">

    <!-- Ügyfelek -->

    <ugyfel ugyfelid="1">
        <nev>
            <vezeteknev>Kovács</vezeteknev>
            <keresztnev>Anna</keresztnev>
        </nev>
        <lakcim>
            <iranyitoszam>1111</iranyitoszam>
            <varos>Budapest</varos>
            <kozterneve>Kossuth út</kozterneve>
            <hazszam>12</hazszam>
        </lakcim>
        <telefonszam>+36301234567</telefonszam>
        <email>anna.kovacs@example.com</email>
    </ugyfel>
    
    <!-- Ügy-Re -->

    <ugyre megjegyzesid="1" rendelesid="10" ugyfelid="1">
        <megjegyzes>Kérem, minél hamarabb szállítsák ki a terméket!</megjegyzes>
    </ugyre>

    <!-- Rendelések -->

    <rendeles fizetestipusa="online" rendelesid="1" statusz="fizetésre vár" szallitoid="3" ugyfelid="11">
        <osszeg>7067.46</osszeg>
        <datum>2023-03-15</datum>
    </rendeles>

    <!-- Rendelt Termékek -->

    <rendelttermek rendelesid="5" rendelttermekid="1" termekid="3">
        <egysegar>1899.50</egysegar>
        <afa>27%</afa>
        <mennyiseg>4</mennyiseg>
    </rendelttermek>

    <!-- Termékek -->

    <termek akcios="nem" termekid="1">
        <nev>Laptop Dell XPS 13</nev>
        <ar>2799.99</ar>
    </termek>

    <!-- Szállítók -->

    <szallito szallitoid="1">
        <nev>Express Shipping Kft.</nev>
        <telefonszam>+36301234567</telefonszam>
        <szallitasiar>500.00</szallitasiar>
        <kozpontcime>
            <iranyitoszam>1055</iranyitoszam>
            <varos>Budapest</varos>
            <kozterneve>Váci út</kozterneve>
            <hazszam>22</hazszam>
        </kozpontcime>
    </szallito>

</webshop>
